version: "3.9"
name: "road_vision__lab3"

services:
#  mqtt:
#    image: eclipse-mosquitto
#    container_name: mqtt_lab3
#    volumes:
#      - ./mosquitto:/mosquitto
#      - ./mosquitto/data:/mosquitto/data
#      - ./mosquitto/log:/mosquitto/log
#    ports:
#      - 1883:1883
#      - 9001:9001
#    networks:
#      mqtt_network:


  postgres_db:
    image: postgres:latest
    container_name: postgres_db_lab3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    volumes:
      - postgres_data_lab3:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - "5432:5432"
    networks:
      db_network:


  pgadmin:
    container_name: pgadmin4_lab3
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data_lab3:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      db_network:


  store:
    container_name: store_lab3
    build: ../../Lab2
    depends_on:
      - postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      db_network:
      hub_store:


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      hub_redis:


  hub:
    container_name: hub
    build: ../
    depends_on:
#      - mqtt
      - redis
      - store
    environment:
      STORE_API_HOST: "store"
      STORE_API_PORT: 8000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
#      MQTT_BROKER_HOST: "mqtt"
#      MQTT_BROKER_PORT: 1883
#      MQTT_TOPIC: "processed_data_topic"
      BATCH_SIZE: 10
    ports:
      - "9000:8000"
    networks:
      hub_store:
      hub_redis:
#      mqtt_network:



networks:
  db_network:
  hub_store:
  hub_redis:


volumes:
  postgres_data_lab3:
  pgadmin-data_lab3:
  